/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Page002Test {
    @Test void appHasAMessage() {
        Page002 classUnderTest = new Page002();
        assertNotNull(classUnderTest.getMessage(), "app should have a greeting");
    }
}
